"""
CADBackend Protocol Interface
Defines the stable abstraction layer for parametric CAD backends.
"""

from typing import Protocol, Dict, Any, Tuple, Optional, List
from pydantic import BaseModel


class MassProperties(BaseModel):
    volume_mm3: float
    volume_ml: float
    mass_g: float
    surface_area_mm2: float
    surface_area_cm2: float
    center_of_mass: Tuple[float, float, float]
    bounding_box_min: Tuple[float, float, float]
    bounding_box_max: Tuple[float, float, float]
    # Honesty fields: where did these numbers come from?
    source: str = "UNKNOWN"  # "OCCT_GProp" | "FORMULA_ESTIMATE"


class TopologyCheckResult(BaseModel):
    is_valid: Optional[bool] = None  # None = unknown (no CAD kernel available)
    is_solid: Optional[bool] = None
    is_manifold: Optional[bool] = None
    is_watertight: Optional[bool] = None
    euler_characteristic: Optional[int] = None
    occt_check_status: str = "NOT_EXECUTED"
    validated_by: str = "UNKNOWN"  # "OCCT_BRepCheck_Analyzer" | "UNAVAILABLE_STUB"
    errors: List[str] = []
    warnings: List[str] = []


class CADBackend(Protocol):
    """Protocol interface for parametric CAD backends."""
    backend_name: str
    execution_mode: str  # "REAL_OCCT" | "SIMULATED_GEOMETRY"

    def create_part(self, name: str) -> Any: ...
    def extrude(self, profile: Any, distance: float) -> Any: ...
    def revolve(self, profile: Any, angle_deg: float, axis: str = "Z") -> Any: ...
    def sweep(self, profile: Any, path: Any) -> Any: ...
    def loft(self, profiles: List[Any]) -> Any: ...
    def shell(self, shape: Any, thickness: float, open_faces: Optional[List[str]] = None) -> Any: ...
    def fillet(self, shape: Any, radius: float, edge_selector: Optional[str] = None) -> Any: ...
    def chamfer(self, shape: Any, distance: float, edge_selector: Optional[str] = None) -> Any: ...
    def draft(self, shape: Any, angle_deg: float, pull_direction: Tuple[float, float, float] = (0, 0, 1)) -> Any: ...
    def union(self, shape1: Any, shape2: Any) -> Any: ...
    def cut(self, shape1: Any, shape2: Any) -> Any: ...
    def intersect(self, shape1: Any, shape2: Any) -> Any: ...
    def validate_shape(self, shape: Any) -> TopologyCheckResult: ...
    def mass_properties(self, shape: Any, density_g_cm3: float = 0.90) -> MassProperties: ...
    def bounding_box(self, shape: Any) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]: ...
    def export_step(self, shape: Any, filepath: Optional[str] = None) -> str: ...
    def export_gltf(self, shape: Any, filepath: Optional[str] = None) -> str: ...
