import { MaterialSpecification, CanonicalParameter } from '../types';

export const APPROVED_MATERIALS: Record<string, MaterialSpecification> = {
  PP: {
    id: 'PP',
    name: 'Polypropylene (Homopolymer)',
    grade: 'Moplen HP500N',
    family: 'Polyolefins',
    density: 0.905,
    youngsModulus: 1450,
    yieldStrength: 34,
    tensileStrength: 35,
    thermalShrinkage: 1.6, // 1.5 - 2.0%
    minWallThickness: 0.8,
    maxWallThickness: 3.5,
    recommendedDraftAngle: 1.5,
    meltTemperature: 230,
    moldTemperature: 45,
    costPerKg: 1.85,
    foodContactCertified: true,
    provenance: 'CAMPUS Database ISO 10350-1 / LyondellBasell Spec Sheet v4',
  },
  ABS: {
    id: 'ABS',
    name: 'Acrylonitrile Butadiene Styrene',
    grade: 'Terluran GP-22',
    family: 'Styrenics',
    density: 1.04,
    youngsModulus: 2300,
    yieldStrength: 45,
    tensileStrength: 48,
    thermalShrinkage: 0.6,
    minWallThickness: 1.2,
    maxWallThickness: 4.0,
    recommendedDraftAngle: 2.0,
    meltTemperature: 245,
    moldTemperature: 60,
    costPerKg: 2.70,
    foodContactCertified: false,
    provenance: 'INEOS Styrolution Tech Bulletin 2025-01 / ISO 1872',
  },
  PC: {
    id: 'PC',
    name: 'Polycarbonate (High Impact)',
    grade: 'Makrolon 2805',
    family: 'Polycarbonates',
    density: 1.20,
    youngsModulus: 2400,
    yieldStrength: 65,
    tensileStrength: 70,
    thermalShrinkage: 0.7,
    minWallThickness: 1.5,
    maxWallThickness: 4.5,
    recommendedDraftAngle: 2.0,
    meltTemperature: 300,
    moldTemperature: 90,
    costPerKg: 4.20,
    foodContactCertified: true,
    provenance: 'Covestro Makrolon Certified Sheet ISO 7391',
  },
  PA66_GF30: {
    id: 'PA66_GF30',
    name: 'Polyamide 66 (30% Glass Filled)',
    grade: 'Zytel 70G30HSL',
    family: 'Polyamides',
    density: 1.37,
    youngsModulus: 8500,
    yieldStrength: 175,
    tensileStrength: 180,
    thermalShrinkage: 0.4,
    minWallThickness: 1.5,
    maxWallThickness: 5.0,
    recommendedDraftAngle: 2.5,
    meltTemperature: 295,
    moldTemperature: 95,
    costPerKg: 5.40,
    foodContactCertified: false,
    provenance: 'DuPont Materials Science Zytel Standard ISO 16396',
  },
  POM: {
    id: 'POM',
    name: 'Polyoxymethylene (Acetal)',
    grade: 'Delrin 500P',
    family: 'Polyacetal',
    density: 1.42,
    youngsModulus: 3100,
    yieldStrength: 71,
    tensileStrength: 72,
    thermalShrinkage: 2.0,
    minWallThickness: 1.0,
    maxWallThickness: 3.5,
    recommendedDraftAngle: 2.0,
    meltTemperature: 215,
    moldTemperature: 85,
    costPerKg: 3.80,
    foodContactCertified: true,
    provenance: 'Celanese Hostaform / Delrin ISO 9988',
  },
};

export const INITIAL_PARAMETERS: CanonicalParameter[] = [
  {
    id: 'capacity',
    name: 'Target Volume / Capacity',
    label: 'Capacity',
    value: 400,
    unit: 'ml',
    status: 'LOCKED',
    source: 'USER',
    confidence: 1.0,
    allowedRange: { min: 50, max: 2000 },
    description: 'Internal usable fluid capacity target',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:00Z',
        actor: 'User',
        action: 'Defined in initial Smart Mode specification',
      },
    ],
  },
  {
    id: 'stackable',
    name: 'Nesting / Stackability',
    label: 'Stackable',
    value: true,
    unit: 'boolean',
    status: 'LOCKED',
    source: 'USER',
    confidence: 1.0,
    description: 'Requires taper angle to allow axial stacking clearance',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:00Z',
        actor: 'User',
        action: 'Locked constraint',
      },
    ],
  },
  {
    id: 'wall_thickness',
    name: 'Nominal Wall Thickness',
    label: 'Wall Thickness',
    value: 1.8,
    unit: 'mm',
    status: 'VERIFIED',
    source: 'PROCESS_RULESET:IM_PP_v4',
    rulesetVersion: 'IM_PP_v4.2',
    confidence: 1.0,
    allowedRange: { min: 1.0, max: 3.0 },
    description: 'Uniform nominal shell thickness across container body',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:01Z',
        actor: 'KnowledgeBase',
        action: 'Calculated from PP melt flow and container height',
        ruleReference: 'SPI Molders Guideline Section 4.2',
      },
    ],
  },
  {
    id: 'draft_angle',
    name: 'Parting Draft Angle',
    label: 'Draft Angle',
    value: 1.75,
    unit: 'deg',
    status: 'VERIFIED',
    source: 'PROCESS_RULESET:IM_PP_v4',
    rulesetVersion: 'IM_PP_v4.2',
    confidence: 1.0,
    allowedRange: { min: 1.0, max: 5.0 },
    description: 'Minimum draft along mold core/cavity pull direction',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:01Z',
        actor: 'KnowledgeBase',
        action: 'Assigned for smooth ejection of PP in polished tool',
      },
    ],
  },
  {
    id: 'max_height',
    name: 'Maximum Envelope Height',
    label: 'Max Height',
    value: 120,
    unit: 'mm',
    status: 'LOCKED',
    source: 'USER',
    confidence: 1.0,
    allowedRange: { min: 50, max: 300 },
    description: 'Maximum permitted external height to fit standard storage',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:00Z',
        actor: 'User',
        action: 'Locked upper bound',
      },
    ],
  },
  {
    id: 'bottom_dia',
    name: 'Base Outer Diameter',
    label: 'Base Diameter',
    value: 64,
    unit: 'mm',
    status: 'CALCULATED',
    source: 'GEOMETRY_SOLVER',
    confidence: 1.0,
    allowedRange: { min: 40, max: 100 },
    description: 'Sized to achieve cup holder compatibility (64-68mm)',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:02Z',
        actor: 'GeometrySolver',
        action: 'Analytical frustum volume resolution',
      },
    ],
  },
  {
    id: 'top_dia',
    name: 'Rim Outer Diameter',
    label: 'Rim Diameter',
    value: 82,
    unit: 'mm',
    status: 'CALCULATED',
    source: 'GEOMETRY_SOLVER',
    confidence: 1.0,
    allowedRange: { min: 60, max: 120 },
    description: 'Derived from height, base diameter, and draft taper',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:02Z',
        actor: 'GeometrySolver',
        action: 'Volume balance integration',
      },
    ],
  },
  {
    id: 'fillet_base',
    name: 'Internal Base Fillet Radius',
    label: 'Base Fillet',
    value: 2.0,
    unit: 'mm',
    status: 'VERIFIED',
    source: 'PROCESS_RULESET:IM_PP_v4',
    confidence: 1.0,
    allowedRange: { min: 1.0, max: 4.0 },
    description: 'Stress-concentration reduction at floor-to-wall intersection',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:01Z',
        actor: 'KnowledgeBase',
        action: 'R >= 0.5 * WallThickness rule',
      },
    ],
  },
  {
    id: 'rim_radius',
    name: 'Top Lip Curvature Radius',
    label: 'Rim Radius',
    value: 3.0,
    unit: 'mm',
    status: 'VERIFIED',
    source: 'ERGONOMICS_STD:DIN_66399',
    confidence: 1.0,
    allowedRange: { min: 1.5, max: 5.0 },
    description: 'Drinking comfort and radial hoop stiffness reinforcement',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:01Z',
        actor: 'KnowledgeBase',
        action: 'Reinforced lip curl',
      },
    ],
  },
  {
    id: 'production_quantity',
    name: 'Target Production Run Volume',
    label: 'Batch Quantity',
    value: 100000,
    unit: 'parts',
    status: 'INFERRED',
    source: 'AI_INFERENCE',
    confidence: 0.85,
    allowedRange: { min: 1000, max: 1000000 },
    description: 'Justifies multi-cavity hardened steel (H13) production tool',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:00Z',
        actor: 'AI_Planner',
        action: 'Inferred from "reusable consumer cup" prompt context',
      },
    ],
  },
  {
    id: 'food_contact',
    name: 'Food Contact Regulatory Approval',
    label: 'Food Contact FDA/EU',
    value: true,
    unit: 'boolean',
    status: 'INFERRED',
    source: 'AI_INFERENCE',
    confidence: 0.95,
    description: 'Requires virgin resin without toxic colorants (FDA 21 CFR 177.1520)',
    provenance: [
      {
        timestamp: '2026-09-06T09:00:00Z',
        actor: 'AI_Planner',
        action: 'Inferred from "cup" usage category',
      },
    ],
  },
];

export const INITIAL_CANONICAL_PARAMETERS = INITIAL_PARAMETERS;
