import { OpenSourceRepoEntry } from '../types';

export const OPEN_SOURCE_REPOSITORIES: OpenSourceRepoEntry[] = [
  {
    repository: 'build123d',
    url: 'https://github.com/gumyr/build123d',
    category: 'CAD Kernel Abstraction',
    tier: 'Tier 1',
    decision: 'USE AS DEPENDENCY',
    capabilities: [
      'Parametric B-Rep solid modeling via Python context managers',
      '2D sketch constraints, 3D extrusions, revolves, sweeps, lofts',
      'Booleans, fillets, chamfers, shell operations, draft angles',
      'Algebraic topological selectors and face filters',
      'Direct STEP and glTF / GLB export pipelines',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'Apache-2.0',
    risk: 'Upstream minor API adjustments; version pin required',
    internalInterface: 'CADBackendAdapter (/cad/build123d/)',
    phase: 'Production V1 / MVP Core',
  },
  {
    repository: 'CadQuery',
    url: 'https://github.com/CadQuery/cadquery',
    category: 'CAD Kernel Abstraction / Reference',
    tier: 'Tier 1',
    decision: 'STUDY REFERENCE',
    capabilities: [
      'Workplane fluent method chaining architecture',
      'Selector string query parser engine',
      'Mature STEP import/export workflows',
      'Assembly joints and hierarchy definitions',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'Apache-2.0',
    risk: 'Competing CAD abstractions; keep behind secondary adapter',
    internalInterface: 'CADBackendAdapter (/cad/cadquery/)',
    phase: 'Reference / Secondary Adapter',
  },
  {
    repository: 'Open CASCADE Technology (OCCT)',
    url: 'https://github.com/Open-Cascade-SAS/OCCT',
    category: 'Core B-Rep Geometry Kernel',
    tier: 'Tier 2',
    decision: 'USE AS DEPENDENCY',
    capabilities: [
      'Topological data structure (TopoDS_Shape, TopoDS_Face, etc.)',
      'Analytic and NURBS curves/surfaces',
      'Exact B-Rep boolean algorithms (BRepAlgoAPI)',
      'Topological validity checking (BRepCheck_Analyzer)',
      'Shape healing and repair (ShapeFix_Shape)',
      'STEP ISO 10303 and IGES translation engines',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'LGPL-2.1 with Open CASCADE Exception',
    risk: 'Low-level C++ segmentation faults on degenerate geometry; isolated process required',
    internalInterface: 'OpenCascade C++ (via OCP) / ValidationGate_2',
    phase: 'Production V1 Foundational',
  },
  {
    repository: 'pythonocc-core',
    url: 'https://github.com/tpaviot/pythonocc-core',
    category: 'Low-Level OCCT Python Bindings',
    tier: 'Tier 2',
    decision: 'USE AS DEPENDENCY',
    capabilities: [
      'Direct 1:1 exposure of OCCT C++ classes in Python',
      'Advanced B-Rep topological walks and coedge queries',
      'STEP AP214/AP242 geometric metadata extraction',
      'Exact mass properties and moment of inertia integration',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'LGPL-3.0',
    risk: 'API complexity; system must never depend directly on pythonocc APIs',
    internalInterface: 'OCCTLowLevelService',
    phase: 'Production V1 (Diagnostic & Fallback)',
  },
  {
    repository: 'pythonocc-demos',
    url: 'https://github.com/tpaviot/pythonocc-demos',
    category: 'Engineering Reference Implementation',
    tier: 'Tier 2',
    decision: 'STUDY REFERENCE',
    capabilities: [
      'Working engineering examples for OCCT workflows',
      'Validated scripts for shape healing, tessellation, and surface interrogation',
    ],
    doWeReimplement: false,
    wrapperRequired: false,
    license: 'GPL-3.0 / LGPL-3.0',
    risk: 'Licensing contamination if code copied; study algorithms conceptually only',
    internalInterface: 'N/A (Reference Material)',
    phase: 'R&D Reference',
  },
  {
    repository: 'BRepNet',
    url: 'https://github.com/AutodeskAILab/BRepNet',
    category: 'B-Rep Deep Learning',
    tier: 'Tier 3',
    decision: 'RESEARCH / ADAPT CONCEPTS',
    capabilities: [
      'Neural network operating directly on B-Rep topology (faces, edges, coedges)',
      'Feature segmentation and face classification on STEP models',
      'Topology walk representation matrices',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'Apache-2.0',
    risk: 'Research prototype; latency; do NOT make mandatory for deterministic MVP',
    internalInterface: 'BRepGraphEncoder',
    phase: 'R&D / Phase 2 (V2+)',
  },
  {
    repository: 'UV-Net',
    url: 'https://github.com/AutodeskAILab/UV-Net',
    category: 'Boundary Representation Learning',
    tier: 'Tier 3',
    decision: 'RESEARCH / ADAPT CONCEPTS',
    capabilities: [
      'Surface representation combining 2D UV-grids with face graph message passing',
      'B-Rep topological embeddings for geometric similarity search',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'Apache-2.0',
    risk: 'High computational cost on complex NURBS surfaces',
    internalInterface: 'GeometricSimilarityEngine',
    phase: 'R&D / Phase 2',
  },
  {
    repository: 'PyTorch Geometric',
    url: 'https://github.com/pyg-team/pytorch_geometric',
    category: 'Graph Neural Network Infrastructure',
    tier: 'Tier 3',
    decision: 'USE AS DEPENDENCY',
    capabilities: [
      'High-performance graph deep learning framework',
      'Part Graphs, Face Graphs, Feature Graphs, Assembly Dependency Graphs',
      'Heterogeneous graph convolutions and message passing',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'MIT',
    risk: 'Strictly prohibited from building proprietary graph frameworks; standard dependency',
    internalInterface: 'GraphNeuralCore',
    phase: 'Production ML / Phase 2',
  },
  {
    repository: 'AI CAD',
    url: 'https://github.com/aarohkandy/ai-cad',
    category: 'AI Intent to CAD Planner',
    tier: 'Reference',
    decision: 'STUDY REFERENCE',
    capabilities: [
      'Natural language -> semantic plan -> deterministic CadQuery pipeline',
      'Planner-first architecture verification',
    ],
    doWeReimplement: true,
    wrapperRequired: false,
    license: 'MIT',
    risk: 'Prototype status; our Manufacturing DSL provides formal grammar and typing',
    internalInterface: 'SmartModePlanner',
    phase: 'Phase 0 Reference',
  },
  {
    repository: 'FreeCAD & Code Workbench',
    url: 'https://github.com/FreeCAD/FreeCAD',
    category: 'Engineering Workstation Integration',
    tier: 'Reference',
    decision: 'USE AS DEPENDENCY',
    capabilities: [
      'Full desktop parametric engineering workstation for MVP pilot testing',
      'Native inspection of build123d / CadQuery objects via FreeCAD Code Workbench',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'LGPL-2.1+ / MIT',
    risk: 'Desktop dependencies; keep decoupled from headless server runtime',
    internalInterface: 'DesktopExportService',
    phase: 'Pilot & Engineering Review',
  },
  {
    repository: 'CADGenBench',
    url: 'https://github.com/huggingface/cadgenbench',
    category: 'AI CAD Benchmark Suite',
    tier: 'Benchmark',
    decision: 'BENCHMARK',
    capabilities: [
      'Benchmark fixtures for AI CAD STEP/B-Rep generation fidelity',
      'Validation metrics across dimensional and topological error',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'Apache-2.0',
    risk: 'Benchmark drift; complement with internal 100-part manufacturing suite',
    internalInterface: 'BenchmarkRunner',
    phase: 'Evaluation & Testing',
  },
  {
    repository: 'Elmer FEM',
    url: 'https://github.com/ElmerCSC/elmerfem',
    category: 'Multiphysics Finite Element Solver',
    tier: 'Reference',
    decision: 'USE AS DEPENDENCY',
    capabilities: [
      'Open-source finite element solver for structural mechanics and thermal cooling',
      'CLI batch execution and VTK/VTU output parsing',
    ],
    doWeReimplement: false,
    wrapperRequired: true,
    license: 'GPL-2.0+ (Subprocess CLI isolation)',
    risk: 'Computation time; only invoke when Gate 5.5/6 analytical filters justify',
    internalInterface: 'SimulationSolverAdapter (Gate 8)',
    phase: 'Gate 8 Simulation',
  },
];

export const OPEN_SOURCE_REGISTRY = [
  {
    name: 'build123d',
    repository: 'gumyr/build123d',
    category: 'cad/build123d',
    decision: 'WRAP_BEHIND_ARCHITECTURE',
    license: 'Apache-2.0',
    ourRole: 'Primary CAD backend adapter for parametric B-Rep generation',
    upstreamCommit: 'v0.6.0 (Pinned)',
  },
  {
    name: 'Open CASCADE (OCCT)',
    repository: 'Open-Cascade-SAS/OCCT',
    category: 'occt/ocp',
    decision: 'USE_DIRECTLY',
    license: 'LGPL-2.1 with Exception',
    ourRole: 'Topological B-Rep solid modeler & STEP translator',
    upstreamCommit: 'V7_7_0',
  },
  {
    name: 'CadQuery',
    repository: 'CadQuery/cadquery',
    category: 'cad/cadquery',
    decision: 'STUDY_REFERENCE',
    license: 'Apache-2.0',
    ourRole: 'Reference for workplane selectors and fluent chaining',
    upstreamCommit: '2.4.0',
  },
  {
    name: 'PyTorch Geometric',
    repository: 'pyg-team/pytorch_geometric',
    category: 'ml/pyg',
    decision: 'USE_DIRECTLY',
    license: 'MIT',
    ourRole: 'Graph neural network learning on B-Rep Face/Edge graphs',
    upstreamCommit: '2.5.0',
  },
  {
    name: 'Lark Parser',
    repository: 'lark-parser/lark',
    category: 'parsers/lark',
    decision: 'USE_DIRECTLY',
    license: 'MIT',
    ourRole: 'LALR(1) parsing for Manufacturing DSL into typed AST',
    upstreamCommit: '1.1.9',
  },
  {
    name: 'Elmer FEM',
    repository: 'ElmerCSC/elmerfem',
    category: 'simulation/elmer',
    decision: 'WRAP_BEHIND_ARCHITECTURE',
    license: 'GPL-2.0 (Subprocess isolation)',
    ourRole: 'Multiphysics finite element solver for Gate 8 validation',
    upstreamCommit: 'Release-9.0',
  },
];

export const DATASET_REGISTRY = [
  {
    name: 'Fusion 360 Gallery Dataset',
    sourceUrl: 'https://github.com/AutodeskAILab/Fusion360GalleryDataset',
    license: 'Autodesk Research License / Non-Commercial',
    status: 'RESEARCH_ONLY',
    permittedUse: 'Academic Research Only (Prohibited for Commercial Training)',
    commercialTrainingPermitted: false,
  },
  {
    name: 'ABC Dataset (A Big CAD Model Dataset)',
    sourceUrl: 'https://archive.nyu.edu/handle/2451/60057',
    license: 'MIT',
    status: 'APPROVED',
    permittedUse: 'B-Rep geometric parsing benchmark & representation learning',
    commercialTrainingPermitted: true,
  },
  {
    name: 'CADGenBench Benchmark Suite',
    sourceUrl: 'https://github.com/huggingface/cadgenbench',
    license: 'Apache-2.0',
    status: 'APPROVED',
    permittedUse: 'Automated evaluation suite for parametric solid fidelity',
    commercialTrainingPermitted: true,
  },
  {
    name: 'IM-100 Injection Molding Ground-Truth Suite',
    sourceUrl: 'Internal Proprietary CAD Engineering Library',
    license: 'Internal Proprietary / Planned Suite',
    status: 'PLANNED',
    permittedUse: 'Planned ground-truth regression suite for Gate 0 through Gate 11',
    commercialTrainingPermitted: true,
  },
];

export const REPRESENTATIVE_FORK_REGISTRY = [
  {
    package: 'build123d',
    strategy: 'No Fork (Upstream Pin + Adapter Wrapper)',
    justification:
      'All custom semantic face tagging (@sidewall_ext, @base_floor) is implemented inside our CADBackendAdapter wrapper without altering build123d core classes.',
    upstreamPr: 'N/A (Zero fork maintained)',
    exitCondition: 'Retain adapter abstraction indefinitely.',
  },
  {
    package: 'pythonocc-core / OCCT',
    strategy: 'Upstream Container Pin',
    justification:
      'Standard LGPL-2.1 with Open CASCADE Exception permits dynamic linking without copyleft leakage. All calls routed through isolated worker subprocess.',
    upstreamPr: 'N/A',
    exitCondition: 'Track LTS releases.',
  },
];
